language: ruby
sudo: false

cache:
  bundler: true

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - 2.5.0
  - ruby-head

gemfile:
  - gemfiles/rails5_0_0.gemfile
  - gemfiles/rails5_0_1.gemfile
  - gemfiles/rails5_0_2.gemfile
  - gemfiles/rails5_0_3.gemfile
  - gemfiles/rails5_0_4.gemfile
  - gemfiles/rails5_0_5.gemfile
  - gemfiles/rails5_1_0.gemfile
  - gemfiles/rails5_1_1.gemfile
  - gemfiles/rails5_1_2.gemfile
  - gemfiles/rails5_1_3.gemfile
  - gemfiles/rails5_1_4.gemfile
  - gemfiles/rails_edge.gemfile

env:
  - SETUP_TASK=turntable:db:reset BUILD_TASK=spec
  - SETUP_TASK=turntable:activerecord:setup BUILD_TASK=turntable:activerecord:test

services:
  - docker

before_install:
  # TODO: use Docker container katsubushi/katsubushi
  # In this test, memcached is used as a dummy katsubushi.
  # Since a binary protocol pull request for katsubushi is not merged yet.
  # After the pull request merged, katsubushi container is available for test.
  - docker run -d --name turntable-memcached -p 11212:11211 memcached:1.5-alpine
  - gem update --system

before_script:
  - bundle exec rake $SETUP_TASK

script:
  - bundle exec rake $BUILD_TASK

matrix:
  exclude:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.3.4
  include:
    - rvm: ruby-head
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.3.4
      gemfile: gemfiles/rails5_1_4.gemfile
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
