language: ruby
sudo: false

cache:
  bundler: true

rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head

gemfile:
  - gemfiles/rails5_0_0.gemfile
  - gemfiles/rails5_0_1.gemfile
  - gemfiles/rails5_0_2.gemfile
  - gemfiles/rails5_0_3.gemfile
  - gemfiles/rails5_0_4.gemfile
  - gemfiles/rails5_0_5.gemfile
  - gemfiles/rails5_0_6.gemfile
  - gemfiles/rails5_0_7.gemfile
  - gemfiles/rails5_1_0.gemfile
  - gemfiles/rails5_1_1.gemfile
  - gemfiles/rails5_1_2.gemfile
  - gemfiles/rails5_1_3.gemfile
  - gemfiles/rails5_1_4.gemfile
  - gemfiles/rails5_1_5.gemfile
  - gemfiles/rails5_1_6.gemfile
  - gemfiles/rails_edge.gemfile

git:
  submodules: false

env:
  - SETUP_TASK=turntable:db:reset BUILD_TASK=spec
  - SETUP_TASK=turntable:db:reset BUILD_TASK=spec SPEC_OPTS="--tag with_katsubushi"
  - SETUP_TASK=turntable:activerecord:setup BUILD_TASK=turntable:activerecord:test UPDATE_SUBMODULE=1

services:
  - docker

before_install:
  - git submodule update --init --recursive --depth 1
  - docker run -d --name turntable-katsubushi -p 11212:11212 katsubushi/katsubushi:latest -worker-id 1
  - gem update --system
  - gem install bundler --no-doc

before_script:
  - bundle exec rake $SETUP_TASK

script:
  - bundle exec rake $BUILD_TASK

matrix:
  exclude:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.2.10
    - rvm: 2.3.7
    - rvm: 2.4.4
  include:
    - rvm: 2.2.10
      gemfile: gemfiles/rails5_0_7.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/rails5_1_6.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/rails5_1_6.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/rails5_1_6.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
