language: ruby
sudo: false

cache:
  bundler: true

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head

gemfile:
  - gemfiles/rails5_0_0.gemfile
  - gemfiles/rails5_0_1.gemfile
  - gemfiles/rails5_0_2.gemfile
  - gemfiles/rails5_0_3.gemfile
  - gemfiles/rails5_0_4.gemfile
  - gemfiles/rails5_0_5.gemfile
  - gemfiles/rails5_1_0.gemfile
  - gemfiles/rails5_1_1.gemfile
  - gemfiles/rails5_1_2.gemfile
  - gemfiles/rails5_1_3.gemfile
  - gemfiles/rails_edge.gemfile

env:
  - SETUP_TASK=turntable:db:reset BUILD_TASK=spec
  - SETUP_TASK=turntable:activerecord:setup BUILD_TASK=turntable:activerecord:test

before_install: gem update --system

before_script:
  - bundle exec rake $SETUP_TASK

script:
  - bundle exec rake $BUILD_TASK

matrix:
  exclude:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.3.4
  include:
    - rvm: ruby-head
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.3.4
      gemfile: gemfiles/rails5_1_3.gemfile
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
