language: ruby
rvm:
  - 2.2
  - 2.3.1
  - ruby-head
gemfile:
  - gemfiles/rails5_0.gemfile
before_script:
  - bundle exec rake turntable:db:reset
script: bundle exec rake spec
matrix:
  allow_failures:
    - rvm: ruby-head
sudo: false
cache: bundler
