default: &default
  adapter: mysql2
  username: root
  password:
  host: localhost
  port: 3306
  encoding: utf8
  database: turntable_test

test:
  <<: *default
  database: turntable_test
  seq:
    user_seq:
      <<: *default
      database: turntable_user_seq_test
  shards:
    user_shard_1:
      <<: *default
      database: turntable_user_shard_1_test
    user_shard_2:
      <<: *default
      database: turntable_user_shard_2_test
    user_shard_3:
      <<: *default
      database: turntable_user_shard_3_test
